### ISSUE TITLE
NPM Install fails on Win7

### ISSUE THREAD

**Issue by paul42** [mal/forsake#1]
Attempting to install, both with and without the --msvs_version=2013
npm-debug.log in  https://gist.github.com/paul42/d18babaed6a9e4e3ae26
but mostly it's:
forsaken.obj : error LNK2001: unresolved external symbol SSL_library_init [C:\code\Tiberium\node_module s\forsake\build\forsaken.vcxproj]
forsaken.obj : error LNK2001: unresolved external symbol SSL_load_error_strings [C:\code\Tiberium\node_ modules\forsake\build\forsaken.vcxproj]
C:\code\Tiberium\node_modules\forsake\build\Release\forsaken.node : fatal error LNK1120: 2 unresolved e xternals [C:\code\Tiberium\node_modules\forsake\build\forsaken.vcxproj]

I'm able to install the latest ursa@0.8.4, not certain why I can't install this. (trying to install chef-node)

thanks in advance,
Paul

**Comment by mal** [comment]
Unfortunately I don't have a Windows box to test this on, so best I can do for now is stab in the dark a bit. Based on a bit of Googlefu I think it might need another lib file, I've added the requirement to the bindings file on a branch. Please could you try the following, if it works I'll get a patch out ASAP.

```
npm install https://github.com/mal/forsake/archive/windows-compile.tar.gz
```

**Comment by mal** [comment]
I've updated the test branch such that it should work with the latest versions of node and iojs.

**Comment by mal** [comment]
`master` is now passing tests against node 0.8 - 4.0 on both Linux and Windows. I'll give it a day or two in case anything else pops up and then I'll cut a release.

**Comment by mal** [comment]
`0.1.3` should work happily with windows.
