### ISSUE TITLE
forsake build error on node 10 and node12

### ISSUE THREAD

**Issue by kathuriaas** [mal/forsake#4]
I am using rhel7 on an openshift container. With node8, forsake module installs successfully. However, when node10 or node12 is used, it fails with below error.  I am using forsake as a dependency of "chef" module. Can you please help?

```
 npm verb node v12.16.1
 npm verb npm  v6.13.4
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! forsake@0.1.4 install: `node-gyp configure build`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the forsake@0.1.4 install script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mal** [comment]
Just pushed an update to add compat for node versions 8 through 14 which should hopefully take care of this. :)
